version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11.1
    working_directory: /go/src/k8s.io/kubernetes
    steps:
    - checkout
    - run: go build ./cmd/kubectl
  test:
    docker:
    - image: circleci/golang:1.11.1
    working_directory: /go/src/k8s.io/kubernetes
    steps:
    - checkout
    - run: go test ./pkg/controller
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
          requires:
            - build
    - deploy-job:
        steps:
          - add_ssh_keys:
              fingerprints:
                - "SO:ME:FIN:G:ER:PR:IN:T"   
                requires:
                  -test
